apiVersion: 1

datasources:
  - name: CacheStats
    uid: cache-stats
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: http://article-cache-service:80
    isDefault: true
    editable: true

